services:
  redis:
    image: redis:alpine
    container_name: tank_game_redis
    restart: always
    ports:
      # แมปพอร์ต Host (เครื่องครู: 6379) เข้ากับ Port ภายใน Container (Redis: 6379)
      - "6379:6379"
    
    # คำสั่งตั้งค่าการทำงานของ Redis Server สำหรับ Streaming Load
    command: >
      redis-server 
      --save "" 
      --appendonly no 
      --maxmemory 512mb 
      --maxmemory-policy noeviction 
      --client-output-buffer-limit normal 0 0 0 
      --tcp-backlog 512 
      --loglevel notice